# render.yaml

services:
  - type: web
    name: web
    runtime: python
    rootDir: IzvorniKod/Digitalizacija
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr
      pip install -r requirements.txt
      python3 manage.py migrate
    startCommand: gunicorn Digitalizacija.wsgi
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
    plan: free
  - type: web
    name: frontend
    runtime: static
    rootDir: IzvorniKod/reactapp
    buildCommand: npm run build;npm install serve
    startCommand: serve -s build
    staticPublishPath: ./build
    plan: free
databases:
  - name: database
    plan: free

